inherit_from: ~/.config/rubocop/config.yml

#
# This file contains temporary ignore statements to shut down warnings 
# about stuff that is already scheduled for refactoring. 
#

Layout/ParameterAlignment:
  Enabled: false
